{% set name = "aiomysql" %}
{% set version = "0.0.20" %}
{% set sha256 = "d89ce25d44dadb43cf2d9e4603bd67b7a0ad12d5e67208de013629ba648df2ba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pymysql >=0.9.0,<=0.9.2

test:
  imports:
    - aiomysql

about:
  home: https://github.com/aio-libs/aiomysql
  summary: "aiomysql is a library for accessing a MySQL database from the asyncio"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
