{% set name = "aiomysql" %}
{% set version = "0.0.22" %}
{% set sha256 = "9bcf8f26d22e550f75cabd635fa19a55c45f835eea008275960cb37acadd622a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pymysql >=0.9.0,<=0.9.2

test:
  imports:
    - aiomysql

about:
  home: https://github.com/aio-libs/aiomysql
  summary: aiomysql is a library for accessing a MySQL database from the asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
