{% set name = "aiomysql" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef04453a3a3ecbd670f813e09d3944d15845b572b34caef3ff715c0140e1ae21

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - pymysql >=1.0
  run:
    - python >=3.7
    - pymysql >=1.0

test:
  imports:
    - aiomysql

about:
  home: https://github.com/aio-libs/aiomysql
  summary: aiomysql is a library for accessing a MySQL database from the asyncio
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
