travis:
  secure:
    BINSTAR_TOKEN: Jom8Y4qr2nGOg2J/wLzM5wulp361aPlqsG5jJb0ND76cKRJevZM0iwU0u1UJ6eg+ZhvTglB2iPmcM2TOgC3wP8MFta5K41lZ0lHGhUHhjp3LUgccwNbtZ+WhckKUC7aTWQjC9FSxqALSXBPeoeY8E6YQYP4gVy+1qQzG56nBvwZ2clVPMoLmPXbvSbP4W9oKLImhdisyMEduSsyo3GTFGCyi2tLhbaHf/7297e8zV8ZlMVc/aML0onuGL2FxI5WF/QzMW8oTKGdb9HA62tXEegFNtecrwus3Vq6TzdRgJbZYhd85nSVDq8nYoc5BbcmvZcVZxG07gNOQjhb4ObuRvRHvMi5Go5L1G9H0BmVaOvDXp5+u9ssumh5HncEF/jATRtlZhdsEEx9IyjvGHzSYTx1nDLB5tOE5ADEImaaX1HNmEFNGzIuqkco7vnnvDTANv5co8ANSeD7k/w6qVgE2szzM+TAfqETFsRcPHZiYTq4CyD6ILW0W7Dhd48LYzyvf6zjgg5qrGQtYM9aIjZjguZG/APdgNjAbb2RdWrB66PrwQ5egjO/Uf3iupIUYccUXxxNPqV+RP0oVYKgVY1/Slok/ZmIx3jGf+2LWrGr/XdcTs5V/t/gKPOag83nl0qWtSVuq9/VPMCCoc2pef8ye55UszxYUW/+9T4XP/54ZgMc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
